
services:
  coturn:
    image: instrumentisto/coturn
    container_name: coturn
    ports:
      - "3478:3478"         # TURN 기본 포트
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "49160-49200:49160-49200/udp"  # 미디어 릴레이용 포트 범위
    environment:
      - TURN_USER=webrtc
      - TURN_PASSWORD=pass123
    command: >
      --no-stun
      --log-file=stdout
      --lt-cred-mech
      --user=webrtc:pass123
      --realm=localhost
      --external-ip=services.avgmax.in
      --min-port=49160
      --max-port=49200
    networks:
      - testRTC_Network

  backend:
    build: .
    # ports:
    #   - "5000:8080"
    depends_on:
      - coturn
    networks:
      - testRTC_Network

  frontend:
    build: ./FE 
    # ports: 
    #   - "3000:3000"
    depends_on:
      - backend
    networks:
      - testRTC_Network

  nginx:
    image: nginx:latest
    ports:
      - "8082:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - testRTC_Network

networks:
  testRTC_Network:
    driver: bridge